### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by vincenzopalazzo** [parubok/awesome-swing#1]
Hi, 
I am a material-ui-swing contributor and I also wanted to tell you my repo, which is an alternative to the one reported in the readme, this contains a new component that simulates the functioning of an android Toast

[materil-ui-swing](https://github.com/vincenzopalazzo/material-ui-swing)
[toasts-for-swing](https://github.com/vincenzopalazzo/toasts-for-swing)

**Comment by parubok** [comment]
Added. Thanks.
