### ISSUE TITLE
My layered font icon library.

### ISSUE THREAD

**Issue by mimoguz** [parubok/awesome-swing#12]
Hi. I've just extracted the code I use in another project to render multi-layered font icons to its own library, thinking it may be of some use to someone else. Very basic stuff, so I don't know its good enough to be included here. Still, maybe you can take a look: [GitHub link](https://github.com/mimoguz/layeredfonticon).

Thank you for this list btw, it's been very helpful.

**Comment by parubok** [comment]
Thanks! I added your project to the list. Keep up the good work!
