### ISSUE TITLE
Missing a useful library: SwingBoost (Windows only)

### ISSUE THREAD

**Issue by ghost** [parubok/awesome-swing#15]
Hey, I wasn't really sure how I should contribute to this repository but I've realized that it's missing a useful library called [SwingBoost](https://github.com/MomoTheDev/SwingBoost).

**Comment by parubok** [comment]
Hi! Thanks!
The project readme says that the library is deprecated: "You should use the Taskbar API provided by AWT (Java 9+) which is more feature filled and stable. It integrates very well with both AWT & Swing."

So it probably should not be included in this list. 

Still, thank you for suggesting it.
