### ISSUE TITLE
Mobile version doesn't look balanced

### ISSUE THREAD

**Issue by kirill-grouchnikov** [parubok/awesome-swing#3]

**Comment by kirill-grouchnikov** [comment]
![Screenshot_20190601-115446](https://user-images.githubusercontent.com/52874/58750762-40301600-8464-11e9-9402-7331e26acf37.png)

**Comment by kirill-grouchnikov** [comment]
Not sure if there's a way to configure column width in markdown

**Comment by parubok** [comment]
For now, I would not put an effort to fix it.
