### ISSUE TITLE
Update Material UI Swing and related projects info

### ISSUE THREAD

**Issue by metteo** [parubok/awesome-swing#7]
Hi

Please add https://github.com/vincenzopalazzo/material-ui-swing to the list.

@vincenzopalazzo FYI

**Comment by metteo** [comment]
Please ignore, didn't notice it's already there... Sorry.

**Comment by vincenzopalazzo** [comment]
Hi all and Hi @metteo,

Thanks to remember me this place :). I think that the link inside this place are a little changed. For this reason, I will add a couple on the information in this issue.

Hi @parubok, please check the projects before adding it, I want that you will add only the components that you considered useful to have inside your list.

- [SwingSnackBar](https://github.com/material-ui-swing/SwingSnackBar): A personal component, with this component the Toast component, is deprecated, please considers to change a little the signature inside the list;
- [JTextFieldPlaceholder](https://github.com/material-ui-swing/JTextFieldPlaceholder): A personal component;
- [LinkLabelUI](https://github.com/material-ui-swing/LinkLabelUI): A personal component;
- [DarkStackOverflowTheme](https://github.com/material-ui-swing/DarkStackOverflowTheme): a personal theme for material-ui-swing, that you can import such as a personal jar
- [Material-UI-Swing](https://github.com/vincenzopalazzo/material-ui-swing): Considers to update the version at the 1.1.1 (will be released in this week)

All this component are under the [materila-ui-swing](https://github.com/material-ui-swing) organizzation (except material-ui-swing lib).

**Comment by parubok** [comment]
Updated.
