### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Bigdatha** [parubok/awesome-swing#9]
Hi parubok,
may I suggest an addition to your awesome list ?
I am using [OpenHtmlToPdf](https://github.com/danfickle/openhtmltopdf) (an actively maintained fork of Flying Saucer) since the first version and I have had very good experiences with it.
Thanks!

**Comment by parubok** [comment]
Hi Bigdatha!
Thanks for the suggestion (and sorry for the late reply).
Since this list is basically a list of Swing GUI libraries, I think that OpenHtmlToPdf, which is HTML to PDF library, is not in the scope of this list.
Thanks and best regards!
